### ISSUE TITLE
Support for re-encoding media attachments

### ISSUE THREAD

**Issue by PoneyClairDeLune** [mautrix/discord#139]
Since Discord disallowed media access without HMAC which expires after several days, reuploading media attachments (and only media attachments) became pretty much required. To reduce disk usage on the homeserver, adding support for re-encoding non-WebP, JPEG XL and AVIF images into one of the three would be quite nice.

Re-encoding videos would take too much computational resources, those would be better re-uploaded as-is with size limits.

```yaml
    media_patterns:
        enabled: true|attachments|false
        image_format: webp|jxl|avif
        image_lossless: false|true # setting to true will disable following quality settings
        webp_psnr: 56 # signal noise-based adaptive quality encoding
        jxl_distance: 1.5 # perception-based adaptive quality encoding
        jxl_progressive: false|true
        avif_quality: 95
        audio_format: aac|vorbis|opus # Use libfdk_aac instead of the built-in FFmpeg AAC encoder, the built-in one is horrible
        audio_bitrate: 160 # CVBR maximum bitrate, see https://kb.ltgc.cc/ltgc/encode.html#lossy-1 for details
        fallback_max_size: 26214400 # The non-Nitro file size limit, 25 MiB
```
