### ISSUE TITLE
logging settings are not applied

### ISSUE THREAD

**Issue by Lykos153** [mautrix/discord#66]
Steps to reproduce (v0.1.1):

1. Disable the file writer
```yaml
logging:
    min_level: debug
    writers:
    - type: stdout
      format: pretty-colored
```
2. Run the bridge as an unprivileged user which doesn't have write access anywhere.
3. The bridge fails to start because it can't write to `./logs/....`
